### ISSUE TITLE
Keystone's token validation endpoint used by PEP Proxy

### ISSUE THREAD

**Issue by gelas** [ging/fi-ware-pep-proxy#8]
I just installed PEP Proxy and I am trying to validate an access token through it.

PEP Proxy is running on my VM (192.168.112.130) on port 2000, as I configured it that way.

After I authenticate manually with Keystone, I take the subject token it returns and with it I make a GET request on:
> http://192.168.112.130:2000 

putting in as a header with name "X-Auth-Token", as described on the project's home page.

On the Keystone's console, where I can see all requests coming into Keystone, I see one to:
> v3/access-token/{acce-token}

which comes from PEP Proxy's attempt to validate my token.

The result PEP Proxy returns is:
> User token not authorized

even though the token is indeed valid.

On Keystone's API specs, the [/v3/auth/tokens](http://developer.openstack.org/api-ref-identity-v3.html#validateTokens) is the endpoint specified to handle token validation instead of the one that PEP Proxy seems to be using, for which I didn't manage to find documentation somewhere.

Can you please give me some help with it?

Forgive me if I am missing some detail which might be the problem.

**Comment by garcianavalon** [comment]
Hi,

I think your problem is a wrong configuration. Try setting the token_engine option to Keystone if you want to validate against Keystone directly and not throught the IdM portal. https://github.com/ging/fi-ware-pep-proxy/blob/dd516bc12b87228ec56a29ce942328642dbd5758/config.js.template#L41

As you can see here, the validation indeed goes to /v3/auth/tokens. https://github.com/ging/fi-ware-pep-proxy/blob/8f9b09bcff6e3dd00376eeb15eb07fbd094f890a/lib/idm.js#L47

Hope this fixes your issue.
Cheers

**Comment by gelas** [comment]
That's great.
Thanks for the prompt reply.
